{% set name = "jaraco.test" %}
{% set version = "5.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jaraco/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ea799b0a149769a71ab8edd07db8ce72b2a5f34b85d8406e20c8f70df1c51f9d

build:
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools
    - toml
    - pip
    - wheel
  run:
    - python
    - jaraco.functools
    - jaraco.context
    - jaraco.collections

test:
  imports:
    - jaraco.test
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jaraco/jaraco.test
  summary: Testing support by jaraco
  description: This package provides functions and fixtures for facilitating tests.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://github.com/jaraco/jaraco.test
  dev_url: https://github.com/jaraco/jaraco.test

extra:
  recipe-maintainers:
    - jan-janssen
